name: Restart Docker container on push

on:
  push:
    branches: [master]

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Restart app container on remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa_docker
            ssh-add -l
            export DOCKER_BUILDKIT=1
            cd /opt/vps-stack-compose
            echo "🔨 Собираем образ..."
            docker compose build --no-cache todo_nestjs
            echo "🚀 Перезапускаем контейнер..."
            docker compose up -d --force-recreate todo_nestjs
            docker image prune -f
            docker images --filter "dangling=true" --no-trunc
